### ISSUE TITLE
Demo working?

### ISSUE THREAD

**Issue by webbrandon** [ZainlessBrombie/yew-examples-redone#1]
I saw your some of your example pages and wanted to give your examples a try.  Seems i was able to build using the `./build.sh` script provided then ran `cargo web build` and `cargo web start`.  Everything is good except there is nothing displaying.  Looking further at code it seems you have it so we can just switch example components in `lib.rs` on line 32.  I tried switching to see if maybe it was just the init demo but still get no display.

I am new to yew (not rust) and webassembly so I may be missing something but feel I should be seeing results displayed.

**Comment by webbrandon** [comment]
Never mind.  

`Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="__wbindgen_placeholder__" error: module is not an object or function`

**Comment by webbrandon** [comment]
For anyone else I ended up using `webpack-dev-server`.

**Comment by ZainlessBrombie** [comment]
Hey there :)
These demos are at an early stage and I'll have to redo the build system.
Glad you figured it out though

**Comment by ZainlessBrombie** [comment]
Alright I uploaded the current commit, which puts all examples on the same page and fixes the build system.
I forgot the state I left this repository in, sorry

**Comment by webbrandon** [comment]
No worries!  These issues helped me get up and running with web assembly and yew ;p Great job by the way. I will link you to what you helped create when I publish the site.
